### ISSUE TITLE
issue with loading library in the universal binary package

### ISSUE THREAD

**Issue by abigmo** [ARPA-SIMC/smnd#5]
Hello,

 on two ubuntu 20.04 desktops when I do the procedure in the manual I have the following error:

``` 
$ wget https://github.com/ARPA-SIMC/smnd/releases/download/v3.0/smnd-3.0_unibin.tar.gz
$ tar -zxvf smnd-3.0_unibin.tar.gz 
$ cd smnd-3.0/
$ ./install_from_bin.sh
$ chmod +x ~/smnd_profile
$ . ~/smnd_profile
$ cd .. 
$ smnd-3.0/bin/vg6d_getpoint --lon=10.9202 --lat=44.6568 --trans-type=inter --sub-type=near --output-format=native downloads/cosmo-2I_er.202207140000.grib ./out.grib

smnd-3.0/bin/vg6d_getpoint: error while loading shared libraries: libsim_volgrid6d.so.12: cannot open shared object file: No such file or directory
```
 The environmental variables do not appear to be correctly exported by sourcing smnd_profile.

After adding manually the env. variables to .bashrc according to the indication under `local installation under path` of the code `install_from_bin.sh` the error changes to:

`smnd-3.0/bin/vg6d_getpoint: error while loading shared libraries: libeccodes_f90.so.0.1: cannot open shared object file: No such file or directory`

even if the directory `smnd-3.0/lib64` is in the LD_LIBRARY_PATH.

Any hint?

Thanks

 AB

**Comment by dcesari** [comment]
```
$ wget https://github.com/ARPA-SIMC/smnd/releases/download/v3.0/smnd-3.0_unibin.tar.gz
$ tar -zxvf smnd-3.0_unibin.tar.gz 
$ cd smnd-3.0/
$ ./install_from_bin.sh
$ chmod +x ~/smnd_profile
$ . ~/smnd_profile
$ cd .. 
```
up to here correct, then you should only use the pure executable name
```
$ vg6d_getpoint --lon=10.9202 --lat=44.6568 --trans-type=inter --sub-type=near --output-format=native downloads/cosmo-2I_er.202207140000.grib ./out.grib
```
using the `PATH` set in smnd_profile. This looks for the executables in `unibin/` which are shell wrappers to the real executables and do all the 'magic' required.

**Comment by abigmo** [comment]
Great! 
It works with COSMO-5M, unfortunately with COSMO-2I there are some issues with the V-component of the momentum flux.

This an old issue, already solved here: 
https://github.com/ARPA-SIMC/libsim/issues/88#issuecomment-968878972
